/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Stitch 3 color palette
        "primary": "#002045",
        "primary-container": "#1a365d",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#adc7f7",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001b3c",
        "on-primary-container": "#86a0cd",
        "on-primary-fixed-variant": "#2d476f",
        "secondary": "#1960a3",
        "secondary-container": "#7db6ff",
        "secondary-fixed": "#d3e4ff",
        "secondary-fixed-dim": "#a2c9ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001c38",
        "on-secondary-container": "#00477f",
        "on-secondary-fixed-variant": "#004881",
        "tertiary": "#2d1d00",
        "tertiary-container": "#493100",
        "tertiary-fixed": "#ffdeaa",
        "tertiary-fixed-dim": "#f8bc4b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#cb9524",
        "on-tertiary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#5f4100",
        "surface": "#f7fafc",
        "surface-dim": "#d7dadc",
        "surface-bright": "#f7fafc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f6",
        "surface-container": "#ebeef0",
        "surface-container-high": "#e5e9eb",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#455f88",
        "on-surface": "#181c1e",
        "on-surface-variant": "#43474e",
        "outline": "#74777f",
        "outline-variant": "#c4c6cf",
        "background": "#f7fafc",
        "on-background": "#181c1e",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eef1f3",
        "inverse-primary": "#adc7f7",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Manrope", "Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
